# Generated by Django 4.0.2 on 2022-04-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ensolvers', '0002_alter_todolist_options_todolist_completada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
